[[redirects]]
from = "/confirm-email"
to = "/.netlify/functions/feed-builder?tolkien=:tolkien"
status 200

[[redirects]]
from = "/reset-password"
to = "/.netlify/functions/feed-builder?tolkien=:tolkien"
status = 200
